import { Product, Order } from './types';

import shirt1 from '@/assets/products/shirt-1.jpg';
import pants1 from '@/assets/products/pants-1.jpg';
import glasses1 from '@/assets/products/glasses-1.jpg';
import watch1 from '@/assets/products/watch-1.jpg';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Gradient Fade Shirt',
    description: 'Premium cotton shirt with stunning purple gradient fade. Perfect for customization.',
    price: 89.99,
    category: 'shirts',
    image: shirt1,
    inStock: true,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Purple Fade', 'Blue Fade', 'Sunset'],
    rating: 4.8,
    reviews: 124,
    isCustomizable: true,
    isTrending: true,
    isNew: true,
  },
  {
    id: '2',
    name: 'Classic White Shirt',
    description: 'Timeless white cotton shirt. Customize with your unique designs.',
    price: 79.99,
    category: 'shirts',
    image: shirt1,
    inStock: true,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['White', 'Off-White'],
    rating: 4.6,
    reviews: 89,
    isCustomizable: true,
  },
  {
    id: '3',
    name: 'Slim Fit Navy Pants',
    description: 'Elegant slim fit pants in deep navy blue. Perfect for any occasion.',
    price: 129.99,
    category: 'pants',
    image: pants1,
    inStock: true,
    sizes: ['28', '30', '32', '34', '36'],
    colors: ['Navy', 'Black', 'Charcoal'],
    rating: 4.7,
    reviews: 67,
    isTrending: true,
  },
  {
    id: '4',
    name: 'Chino Pants',
    description: 'Comfortable chino pants for everyday style.',
    price: 99.99,
    category: 'pants',
    image: pants1,
    inStock: true,
    sizes: ['28', '30', '32', '34', '36', '38'],
    colors: ['Khaki', 'Olive', 'Navy'],
    rating: 4.5,
    reviews: 45,
  },
  {
    id: '5',
    name: 'Aviator Sunglasses',
    description: 'Classic aviator style with gradient lenses and gold frame.',
    price: 159.99,
    category: 'glasses',
    image: glasses1,
    inStock: true,
    colors: ['Gold/Rose', 'Silver/Blue', 'Black'],
    rating: 4.9,
    reviews: 203,
    isTrending: true,
    isNew: true,
  },
  {
    id: '6',
    name: 'Round Retro Glasses',
    description: 'Vintage-inspired round glasses for a sophisticated look.',
    price: 139.99,
    category: 'glasses',
    image: glasses1,
    inStock: false,
    colors: ['Tortoise', 'Black', 'Crystal'],
    rating: 4.4,
    reviews: 56,
  },
  {
    id: '7',
    name: 'Luxury Leather Watch',
    description: 'Elegant timepiece with rose gold case and leather strap.',
    price: 299.99,
    category: 'watches',
    image: watch1,
    inStock: true,
    colors: ['Brown Leather', 'Black Leather', 'Navy Leather'],
    rating: 4.9,
    reviews: 178,
    isTrending: true,
  },
  {
    id: '8',
    name: 'Minimalist Steel Watch',
    description: 'Modern minimalist design with stainless steel band.',
    price: 249.99,
    category: 'watches',
    image: watch1,
    inStock: true,
    colors: ['Silver', 'Gold', 'Rose Gold'],
    rating: 4.7,
    reviews: 92,
    isNew: true,
  },
];

export const mockOrders: Order[] = [
  {
    id: 'ORD-001',
    userId: '1',
    items: [
      {
        product: mockProducts[0],
        quantity: 1,
        size: 'M',
        color: 'Purple Fade',
      },
    ],
    status: 'shipped',
    total: 89.99,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-18'),
    shippingAddress: {
      street: '123 Main St',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      country: 'USA',
    },
    paymentMethod: 'Credit Card',
    timeline: [
      { status: 'Order Placed', date: new Date('2024-01-15'), description: 'Your order has been placed' },
      { status: 'Confirmed', date: new Date('2024-01-15'), description: 'Order confirmed via WhatsApp' },
      { status: 'Processing', date: new Date('2024-01-16'), description: 'Your order is being prepared' },
      { status: 'Shipped', date: new Date('2024-01-18'), description: 'Your order is on the way' },
    ],
  },
];

export const tattooElements = [
  { id: '1', name: 'Dragon', image: '/placeholder.svg' },
  { id: '2', name: 'Rose', image: '/placeholder.svg' },
  { id: '3', name: 'Skull', image: '/placeholder.svg' },
  { id: '4', name: 'Eagle', image: '/placeholder.svg' },
  { id: '5', name: 'Lion', image: '/placeholder.svg' },
  { id: '6', name: 'Wolf', image: '/placeholder.svg' },
  { id: '7', name: 'Butterfly', image: '/placeholder.svg' },
  { id: '8', name: 'Phoenix', image: '/placeholder.svg' },
];

export const patternElements = [
  { id: '1', name: 'Stripes', image: '/placeholder.svg' },
  { id: '2', name: 'Dots', image: '/placeholder.svg' },
  { id: '3', name: 'Geometric', image: '/placeholder.svg' },
  { id: '4', name: 'Floral', image: '/placeholder.svg' },
];
